### ISSUE TITLE
Could not build documentation in console mode

### ISSUE THREAD

**Issue by drusa** [Geaz/sharpDox#56] opened 2016-05-13 09:24 UTC
I get this error when i want to create a doc in console mode, like this:
**SharpDox.Console -config c:\...\filename.sdox**. GUI mode is working properly.
Before "Could not build documentation" a ton of .Net errors are thrown. Honestly,i haven't found doc for sharpdox setup so far. Would you help me how to solve above issue?

Thanks for your answers in advance!

Version: 1.0rc2

**Comment by Geaz** [comment] 2016-05-13 09:46
Could you please attach the console logfile? There should be one in the sharpDox folder.

**Comment by drusa** [comment] 2016-05-13 09:47
Sure:
[console-log.txt](https://github.com/Geaz/sharpDox/files/262927/console-log.txt)

**Comment by drusa** [comment] 2016-05-13 09:54
Here is the project file itself as well(in .txt format):
[mancity.txt](https://github.com/Geaz/sharpDox/files/262948/mancity.txt)

**Comment by Geaz** [comment] 2016-05-13 09:56
Thank you! I will try to reproduce this error and will come back to you soon.

**Comment by Geaz** [comment] 2016-05-13 14:44
I was able to reproduce the error in 1.0rc2.
This seems to be a general problem with the console executable in this version. The problem was already fixed in the upcoming release which will follow in the next few days.

**Comment by Geaz** [comment] 2016-05-13 22:24
I just released Version 1.1! Feel free to test the new Version and tell me, if your Problem got fixed. Thank you!

**Closed** 2016-05-17 16:38 UTC
Labels: bug
