### ISSUE TITLE
Output is empty ... ?

### ISSUE THREAD

**Issue by SSiefert** [geaz/sharpDox#95] opened 2018-01-29 18:26 UTC
I assume that I'm doing something wrong. Not sure what ... the output is empty. I'm having a classlibrary-project (net4.6 / vs2017) but the output does not contain any type. The project contains several namespaces, classes and interfaces. I also checked the existing issues ... I'm having an exporter (html) selected.

**Comment by geaz** [comment] 2018-01-30 07:50
The problem is, that sharpDox need to "know" the target framework. Unfortunately it seems like all class libraries in VS2017 are targeting .NET Standard instead of the "old" full framework. This target is an unknown target for sharpDox at the moment and therefore, I assume, you get the empty output.

I will check, if I can change this today. Coming back to you asap.

**Comment by geaz** [comment] 2018-01-30 18:59
The problem should be fixed now. I compiled the relevant dll for you. Please replace the on in the libs folder with the one from the zip and try, if it works.

[SharpDox.Build.dll.zip](https://github.com/geaz/sharpDox/files/1679000/SharpDox.Build.dll.zip)

**Comment by geaz** [comment] 2018-01-30 19:06
I just released a new version which should fix this problem:
https://github.com/geaz/sharpDox/releases/download/v1.2.3/sharpDox.1.2.3.zip

Please test the new version and let me know, if it works.

**Closed** 2018-02-01 22:05 UTC
Labels: bug
